print("kavya")
a=5;b=6
print(a,b)
print(a,b,sep="-->")
print(a,end=" ")
print(b)
print("a=%d b=%d"%(a,b))
print("a={} b={}".format(a,b))
print("a={0} b={1}".format(a,b))
print("b={1} a={0}".format(a,b))
c=input()
print(c)
